# Generated by Django 3.1.2 on 2021-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
