# Generated by Django 3.1.2 on 2021-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210107_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('From', models.CharField(max_length=40)),
                ('via', models.CharField(max_length=40)),
                ('to', models.CharField(max_length=40)),
            ],
        ),
    ]
