# Generated by Django 3.1.2 on 2021-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('breakfast', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('snack', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
            ],
        ),
    ]
