# Generated by Django 3.1.2 on 2021-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_mess_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('sname', models.CharField(max_length=40)),
                ('smobile', models.IntegerField()),
                ('fname', models.CharField(max_length=40)),
                ('fmobile', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('acadmic', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('gov_type', models.CharField(max_length=20)),
                ('gov_id', models.CharField(max_length=20)),
                ('room_block', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=10)),
                ('acc_plan', models.CharField(max_length=20)),
                ('final_fee', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateField(default='2021-01-08'),
        ),
    ]
