# Generated by Django 3.1.2 on 2021-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210108_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_student',
            name='studentid',
            field=models.IntegerField(default=20210001),
        ),
    ]
