# Generated by Django 3.1.2 on 2021-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20210108_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_student',
            name='fmobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='smobile',
            field=models.CharField(max_length=20),
        ),
    ]
