# Generated by Django 3.1.2 on 2021-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_complaint_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='datetime',
            field=models.CharField(default='2021-01-08', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
