# Generated by Django 3.0.5 on 2021-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20210108_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='register_student',
            name='studentid',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='datetime',
            field=models.CharField(default='2021-01-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateField(default='2021-01-10'),
        ),
    ]
